ALTER TABLE CLASSICCARS.ORDERDETAIL DROP CONSTRAINT RDRDETAILPRDCTCODE
ALTER TABLE CLASSICCARS.ORDERDETAIL DROP CONSTRAINT RDRDTLPRCHSRDRNMBR
ALTER TABLE CLASSICCARS.EMPLOYEE DROP CONSTRAINT EMPLOYEEOFFICECODE
ALTER TABLE CLASSICCARS.PAYMENT DROP CONSTRAINT PYMNTCSTOMERNUMBER
DROP TABLE CLASSICCARS.PRODUCTLINE
DROP TABLE CLASSICCARS.OFFICE
DROP TABLE CLASSICCARS.ORDERDETAIL
DROP TABLE CLASSICCARS.EMPLOYEE
DROP TABLE CLASSICCARS.PAYMENT
DROP TABLE CLASSICCARS.PURCHASEORDER
DROP TABLE CLASSICCARS.PRODUCT
DROP TABLE CLASSICCARS.CUSTOMER
